name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v2
        - uses: actions/setup-node@v1
          with:
            node-version: 16.3.0
        - name: Install
          run: npm install
        - name: Test
          with:
            env:
              SAUCELABS_ACCESS_KEY: ${{ secrets.SAUCELABS_ACCESS_KEY }}
              SAUCELABS_USERNAME: ${{ secrets.SAUCELABS_USERNAME }}
          run: npm run test:sauce:android --spec test/specs/login.spec.js
        - uses: actions/upload-artifact@v1
          if: failure()
          with:
            name: logs
            path: logs
