name: CI browserstack
on: [push]
  # push:
  #   branches: [main]
  # pull_request:
  #   branches: [main]
  # workflow dispatch:
  #   inputs:
  #     types:
  #       description: 'Environment (example : local, saucelabs, browserstack)'
  #       required: true
  #       default: "local"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v2
        - uses: actions/setup-node@v1
          with:
            node-version: 16.3.0
        - name: Install
          run: npm install
        - name: Test
          run: npm run test:browserstack:ios --spec test/specs/login.spec.js
          env:
            BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
            BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
        - uses: actions/upload-artifact@v1
          if: failure()
          with:
            name: logs
            path: logs
