name: CI perfecto
on: 
  workflow_dispatch:
    inputs:
      platform:
        type: choice
        description: 'Platform (iOS/Android/both)' 
        required: false
        default: android
        options:
        - android
        - ios
      spec:
        type: choice
        default: all
        options:
          - 1_LOGIN_valid_user.spec
          - 2_LOGIN_locked_out_user.spec
          - 3_LOGIN_invalid_user.spec
          - 4_PRODUCT_onesie.spec
          - all
        description: 'Spec (no file extension needed)'
        required: false
      manufacturer:
        type: choice
        description: 'Manufacturer'
        required: false
        options:
          - Samsung
          - Google
          - Apple
          - iPhone
      model:
        type: choice
        description: 'Model'
        required: false
        options:
          - Galaxy S9
          - Galaxy Tab S3 9.7
          - Pixel 4A \\(5G\\)
          - iPhone-XR
          - iPhone-11 Pro
          - iPhone-13 Mini
      os_version:
        description: 'OS version'
        required: false

permissions:
  contents: write

        
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v2
        - uses: actions/setup-node@v1
          with:
            node-version: 16.3.0
        - name: Install
          run: npm install
        - name: Test
          run: |
            if [[ "${{ github.event.inputs.platform }}" == "android" ]]; then
              if [ "${{ github.event.inputs.spec }}" != 'all'  ]; then
                npm --manufacturer="${{ github.event.inputs.manufacturer }}" --model="${{ github.event.inputs.model }}" --osversion=${{ github.event.inputs.os_version }} run test:perfecto:android -- --spec=./test/specs/**/${{ github.event.inputs.spec }}.js 
              else
                npm --manufacturer="${{ github.event.inputs.manufacturer }}" --model="${{ github.event.inputs.model }}" --osversion=${{ github.event.inputs.os_version }} run test:perfecto:android
              fi
            else
              if [ "${{ github.event.inputs.spec }}" != 'all'  ]; then
                npm --manufacturer="${{ github.event.inputs.manufacturer }}" --model="${{ github.event.inputs.model }}" --osversion=${{ github.event.inputs.os_version }} run test:perfecto:ios -- --spec=./test/specs/**/${{ github.event.inputs.spec }}.js 
              else
                npm --manufacturer="${{ github.event.inputs.manufacturer }}" --model="${{ github.event.inputs.model }}" --osversion=${{ github.event.inputs.os_version }} run test:perfecto:ios
              fi
            fi
          env:
            PERFECTO_SECURITY_TOKEN: ${{ secrets.PERFECTO_SECURITY_TOKEN }}
            PERFECTO_IOS_APP: ${{ secrets.PERFECTO_IOS_APP }}
            PERFECTO_ANDROID_APP: ${{ secrets.PERFECTO_ANDROID_APP }}
        - uses: actions/upload-artifact@v1
          if: failure()
          with:
            name: logs
            path: logs

        - name: Get Allure history
          uses: actions/checkout@v2
          if: success() || failure()
          continue-on-error: true
          with:
            ref: gh-pages
            path: gh-pages

        - name: Test marketplace action
          uses: simple-elf/allure-report-action@master
          if: success() || failure()
          id: allure-report
          with:
            allure_results: allure-results
            gh_pages: gh-pages
            allure_report: allure-report
            allure_history: allure-history
            keep_reports: 10
            subfolder: perfecto-results

        - name: Deploy report to Github Pages
          if: success() || failure()
          uses: peaceiris/actions-gh-pages@v2
          env:
            PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            PUBLISH_BRANCH: gh-pages
            PUBLISH_DIR: allure-history
