name: CI Local
on: [push]

permissions:
    contents: write
  
jobs:
    tests:
      runs-on: ubuntu-latest
      steps:
          - name: Checkout
            uses: actions/checkout@v2
          - uses: actions/setup-node@v1
            with:
              node-version: 16.3.0
          - name: Install
            run: npm install
          - name: Test
            run: npm run test:browserstack:android -- --spec=test/specs/1_LOGIN_valid_user.spec.js
            env:
              BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
              BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
          - uses: actions/upload-artifact@v1
            if: failure()
            with:
              name: logs
              path: logs
  
          - name: Generate Report
            if: success() || failure()
            run: |
             npx allure generate --clean
  
          - uses: actions/upload-artifact@master
            with:
              name: allure-results
              path: allure-results
  
          - name: Get Allure history
            uses: actions/checkout@v2
            if: success() || failure()
            continue-on-error: true
            with:
              ref: gh-pages
              path: gh-pages
  
          - name: Test marketplace action
            uses: simple-elf/allure-report-action@master
            if: success() || failure()
            id: allure-report
            with:
              allure_results: allure-results
              gh_pages: gh-pages
              allure_report: allure-report
              allure_history: allure-history
              keep_reports: 10
              subfolder: browserstack-results
  
          - name: Deploy report to Github Pages
            if: success() || failure()
            uses: peaceiris/actions-gh-pages@v2
            env:
              PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              PUBLISH_BRANCH: gh-pages
              PUBLISH_DIR: allure-history
  