name: CI perfecto
on: 
  workflow_dispatch:
  push:
    branches: [main]
        
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v2
        - uses: actions/setup-node@v1
          with:
            node-version: 16.3.0
        - name: Install
          run: npm install
        - name: Test
          run: npm run test:perfecto:ios
          env:
            PERFECTO_SECURITY_TOKEN: ${{ secrets.PERFECTO_SECURITY_TOKEN }}
            PERFECTO_IOS_APP: ${{ secrets.PERFECTO_IOS_APP }}
            PERFECTO_ANDROID_APP: ${{ secrets.PERFECTO_ANDROID_APP }}
        - uses: actions/upload-artifact@v1
          if: failure()
          with:
            name: logs
            path: logs

        - name: Get Allure history
          uses: actions/checkout@v2
          if: success() || failure()
          continue-on-error: true
          with:
            ref: gh-pages
            path: gh-pages

        - name: Test marketplace action
          uses: simple-elf/allure-report-action@master
          if: success() || failure()
          id: allure-report
          with:
            allure_results: allure-results
            gh_pages: gh-pages
            allure_report: allure-report
            allure_history: allure-history
            keep_reports: 10
            subfolder: perfecto-results

        - name: Deploy report to Github Pages
          if: success() || failure()
          uses: peaceiris/actions-gh-pages@v2
          env:
            PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            PUBLISH_BRANCH: gh-pages
            PUBLISH_DIR: allure-history
