name: CI saucelabs
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  # workflow dispatch:
  #   inputs:
  #     types:
  #       description: 'Environment (example : local, saucelabs, browserstack)'
  #       required: true
  #       default: "local"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v2
        - uses: actions/setup-node@v1
          with:
            node-version: 16.3.0
        - name: Install
          run: npm install
        - name: Test
          run: npm run test:saucelabs:android --spec test/specs/login.spec.js
          env:
            SAUCELABS_ACCESS_KEY: ${{ secrets.SAUCELABS_ACCESS_KEY }}
            SAUCELABS_USERNAME: ${{ secrets.SAUCELABS_USERNAME }}
        - uses: actions/upload-artifact@v1
          if: failure()
          with:
            name: logs
            path: logs
