name: CI saucelabs
on: 
  workflow_dispatch:
  push:
    branches: [main]
  # push:
  #   branches: [main]
  # pull_request:
  #   branches: [main]
  # workflow dispatch:
  #   inputs:
  #     types:
  #       description: 'Environment (example : local, saucelabs, browserstack)'
  #       required: true
  #       default: "local"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v2
        - uses: actions/setup-node@v1
          with:
            node-version: 16.3.0
        - name: Install
          run: npm install
        - name: Test
          run: npm run test:saucelabs:android --spec test/specs/login.spec.js
          env:
            SAUCELABS_ACCESS_KEY: ${{ secrets.SAUCELABS_ACCESS_KEY }}
            SAUCELABS_USERNAME: ${{ secrets.SAUCELABS_USERNAME }}
        - uses: actions/upload-artifact@v1
          if: failure()
          with:
            name: logs
            path: logs

        - name: Get Allure history
          uses: actions/checkout@v2
          if: success() || failure()
          continue-on-error: true
          with:
            ref: gh-pages
            path: gh-pages

        - name: Test marketplace action
          uses: simple-elf/allure-report-action@master
          if: success() || failure()
          id: allure-report
          with:
            allure_results: allure-results
            gh_pages: gh-pages
            allure_report: allure-report
            allure_history: allure-history
            keep_reports: 10
            subfolder: saucelabs-results

        - name: Deploy report to Github Pages
          if: success() || failure()
          uses: peaceiris/actions-gh-pages@v2
          env:
            PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            PUBLISH_BRANCH: gh-pages
            PUBLISH_DIR: allure-history
