name: CI uftm
on: 
  workflow_dispatch:
    inputs:
      platform:
        type: choice
        description: 'Platform (iOS/Android/both)'
        required: false
        default: android
        options:
        - android
        - ios
      spec:
        type: choice
        default: all
        options:
          - 1_LOGIN_valid_user.spec
          - 2_LOGIN_locked_out_user.spec
          - 3_LOGIN_invalid_user.spec
          - 4_PRODUCT_onesie.spec
          - all
        description: 'Spec (no file extension needed)'
        required: false
     
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v2
        - uses: actions/setup-node@v1
          with:
            node-version: 16.3.0
        - name: Install
          run: npm install
        - name: Test
          run: |
            if [[ "${{ github.event.inputs.platform }}" == "android" ]]; then
              if [ "${{ github.event.inputs.spec }}" != 'all'  ]; then
                npm run test:uftm:android -- --spec=./test/specs/**/${{ github.event.inputs.spec }}.js 
              else
                npm run test:uftm:android
              fi
            else
              if [ "${{ github.event.inputs.spec }}" != 'all'  ]; then
                npm run test:uftm:ios -- --spec=./test/specs/**/${{ github.event.inputs.spec }}.js 
              else
                npm run test:uftm:ios
              fi
            fi
          env:
            UFTM_ACCESS_KEY: ${{ secrets.UFTM_ACCESS_KEY }}
            UFTM_USERNAME: ${{ secrets.UFTM_USERNAME }}
        - uses: actions/upload-artifact@v1
          if: failure()
          with:
            name: logs
            path: logs

        - name: Get Allure history
          uses: actions/checkout@v2
          if: success() || failure()
          continue-on-error: true
          with:
            ref: gh-pages
            path: gh-pages

        - name: Test marketplace action
          uses: simple-elf/allure-report-action@master
          if: success() || failure()
          id: allure-report
          with:
            allure_results: allure-results
            gh_pages: gh-pages
            allure_report: allure-report
            allure_history: allure-history
            keep_reports: 10
            subfolder: uftm-results

        - name: Deploy report to Github Pages
          if: success() || failure()
          uses: peaceiris/actions-gh-pages@v2
          env:
            PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            PUBLISH_BRANCH: gh-pages
            PUBLISH_DIR: allure-history
